name: Regression
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "tag=$(date --date='yesterday' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "date=$(date --date='yesterday' +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          sudo apt-get install build-essential libboost-dev autoconf gperf
      - name: Install iverilog
        run: |
          git clone https://github.com/steveicarus/iverilog.git
          cd iverilog; git checkout --track -b v11-branch origin/v11-branch; git pull; sh autoconf.sh; ./configure; make -j `nproc`; sudo make install
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: SoCKat
      - name: Install sbt
        run: curl -fL https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup -y
      - name: Get oss-cad-suite
        run: |
          wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/${{ steps.date.outputs.tag }}/oss-cad-suite-linux-x64-${{ steps.date.outputs.date }}.tgz
          tar xzvf oss-cad-suite-linux-x64-${{ steps.date.outputs.date }}.tgz
          export PATH="<extracted_location>/oss-cad-suite/bin:$PATH"
      - name: Launch regression
        run: |
          source $GITHUB_WORKSPACE/oss-cad-suite/environment
          make -C SoCKat ddr3 regression SBT_BIN=/usr/bin/sbt IVERILOG_BIN=$GITHUB_WORKSPACE/oss-cad-suite/bin/iverilog VVP_BIN=$GITHUB_WORKSPACE/oss-cad-suite/bin/vvp